# --- General options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a simple GitHub user page (http://username.github.io) then use these settings:
#url: "http://dpseidel.github.io"
#baseurl: ""

# If you are building a GitHub project page then use these settings:
url: "http://dpseidel.github.io/MovEco-R-Workshop"
baseurl: "/MovEco-R-Workshop"

# Of course don't forget to change the username and projectname to YOUR username and project

# Name of website
title: HKU Movement Eco in R Workshop

# Short description of your site
description: The homepage for the Movement Ecology in R Workshop hosted at Hong Kong University, January 3-12, 2018 

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  Logistics & Prep: "Logistics_Prep"
  Schedule: "Schedule.pdf"
  Lectures:
    - Introduction and Goals: "Materials/Day1/HongKongMovement2018Lec1.pdf"
    - Movement Ecology - An Overview: "Materials/Day2/HongKongMovement2018Lec2.pdf"
    - Home Range Estimation: "Materials/Day3/HongKongMovement2018Lec3.pdf"  
    - Space Time Considerations: "Materials/Day4/HongKongMovement2018Lec4.pdf"  
    - Modelling Habitat Selection: "Materials/Day5/HongKongMovement2018Lec5.pdf" 
    - Behavioral Analysis: "Materials/Day6/HongKongMovement2018Lec6.pdf"  
    - Simulating Movement: "Materials/Day7/HongKongMovement2018Lec7.pdf"  
  Live Code Tutorials:
    - Basics in R: "Materials/Day1/Basics_in_R"
    - Basics 2 in R: "Materials/Day1/More_Advanced_R" 
    - Spatial Data in R: "Materials/Day2/Spatial_Data_in_R"
    - Analysing Movement Data: "Materials/Day2/Movement_Data_Path_Metrics"
    - HomeRanges - MCP & KDE: "Materials/Day3/HomeRanges"
    - HomeRanges - LoCoH: "Materials/Day3/LoCoH" 
    - HomeRanges - LoCoh2 & BB: "Materials/Day4/MoreThoughts_LoCoh_BB"
    - SpaceTime - t-LoCoH: "Materials/Day5/TLoCoH"
    - SpaceTime - t-LoCoH 2: "Materials/Day5/TLoCoH_and_Beyond"
    - Behavioral Analysis: "Materials/Day6/Behavioral_Analysis"
    - Movement Syndromes: "Materials/Day6/Syndromes"
    - Simulating Movement Part 1: "Materials/Day7/Simulating_Movement"
    - Simulating Movement Part 2: "Materials/Day7/Simulating_Movement_part2"
  Activities:
    - Day 1: "Materials/Day1/Day1_Activities"
    - Day 2: "Materials/Day2/Day2_Activity"
    - Day 3: "Materials/Day3/Day3_Activity"
    - Day 4: "Materials/Day4/Day4_Activity"
    - Day 5: "Materials/Day5/Day5_Activity"
  Extra Materials: "extra"
  #Search: "search"

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
# avatar: "/img/logo.png"

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
title-img: "/MovEco-R-Workshop/img/banner.png"

# --- Background colour/image options --- #

# Personalize the colors in your website. Colour values can be any valid CSS colour

navbar-col: "#FFFFFF"
navbar-text-col: "#9ebcda"
navbar-children-col: "#f7fcfd"
page-col: "#FFFFFF"
link-col: "#810f7c"
hover-col: "#0085A1"
footer-col: "#FFFFFF"
footer-text-col: "#777777"
footer-link-col: "#595959"

# Alternatively, the navbar, footer, and page background can be set to use background images
# instead of colour

#navbar-img: "/img/HMB.jpg"
#footer-img: "/img/HMB.jpg"
#page-img: "/img/bgimage.png"

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Dana Paige Seidel

# Select your active Social Network Links.
# Uncomment the links you want to show in the footer and add your information to each link.
# You can reorder the items to define the link order.
# If you want to add a new link that isn't here, you'll need to also edit the file _data/SocialNetworks.yml
social-network-links:
  #rss: true
  email: "dpseidel@berkeley.edu"
  #facebook: 
  github: dpseidel/MovEco-R-workshop
#  twitter: VLSB5048
#  reddit: yourname
#  google-plus: +DeanAttali
#  linkedin: daattali
#  xing: yourname
#  stackoverflow: "3943160/daattali"
#  snapchat: deanat78
#  instagram: deanat78
#  youtube: user/deanat78
#  spotify: yourname
#  telephone: +14159998888
#  steam: deanat78
#  twitch: yourname
#  yelp: yourname

# Select which share links to show in posts
share-links-active:
  twitter: true
  facebook: false
  google: false
  linkedin: false

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
#url-pretty: "MyWebsite.com"  # eg. "deanattali.com/beautiful-jekyll"

# --- Web Statistics Section --- #

# Fill in your Google Analytics ID to track your website using GA
#google_analytics: ""

# Google Tag Manager ID
#gtm: ""

# Matomo (aka Piwik) Web statistics
# Uncomment the following section to enable Matomo. The opt-out parameter controls
# whether or not you want to allow users to opt out of tracking.

#matomo:
#  site_id: "9"
#  uri: "demo.wiki.pro"
#  opt-out: true

# --- Misc --- #
# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
#disqus: ""

# Facebook App ID
# fb_app_id: ""

# Excerpt Word Length
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50

# Character used to separate site title and description in HTML document title
# and RSS feed title
title-separator: "-"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "America/Vancouver"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Use tags index page and make tags on each post clickable
link-tags: true

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile

# prose.io config
prose:
  rooturl: '_posts'
  media: 'img'
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /img
    - /js
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "subtitle"
        field:
          element: "textarea"
          label: "Subtitle"
          placeholder: "A description of your post."
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date"
          help: "Enter date of post."
          placeholder: "yyyy-mm-dd"
          alterable: true
      - name: "image"
        field:
          element: "text"
          label: "Image"
          help: "Add a thumbnail image to your post."
          placeholder: "Thumbnail"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          help: "Check to publish post, uncheck to hide."

plugins:
  - jekyll-paginate

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
