---
title: Workshop Schedule
author: Dana Seidel & Eric Dougherty
output: github_document
---

# Week 1
## Day 1,  Jan 3
### Topics to Cover
- Basic Workflow
- Data manipulation & visualization with tidyverse
- Custom Functions
- For loops, apply functions
- Intro to Simulation 

### Supplement Reading:
Much of the days workflow is a much abbreviated version of the [Data Science for R book](http://r4ds.had.co.nz/).
This is an excellent resource for anyone wrangling data in R. 

### Schedule 
| Time | Activity | Speaker | Topic |
| ------------- | --------------- | --- | ------------------------------------ |
| 9:00 – 10:30 | Lecture | DPS, ERD |  Introductions and Goals |
| 10:30 – 10:45 | Morning Break | | |
| 10:45 – 12:00 | Livecode | DPS | Basics in R (R Studio; importing, exporting, cleaning data; data classes) | 
| 12:00 – 13:30 | Lunch | | |
| 13:30 – 14:45 | Livecode| DPS | Slightly more advanced R (custom functions, flexible arguments, loops) |
| 14:45 – 15:00 | Afternoon Break | | |
| 15:00 – 16:30 | Hands on | | Practice manipulating raw data |

## Day 2, Jan 4

### Topics to cover
- Introduce movement data
- Vectors/rasters
- Spatial data in R (sf, sp libraries)
- Projections, transformations
- Movebank library (move package)
- visualizing movement data (mapview, ggplot +geom_sf)
- adehabitat, ltrajs, path statistics

### Schedule
| Time | Activity | Speaker | Topic |
| ------------- | --------------- | --- | ------------------------------------ |
| 9:00 – 10:30 | Lecture | DPS/ERD |   Overview of Movement Ecology and Analyses |
| 10:30 – 10:45 | Morning Break | | |
| 10:45 – 12:00 | Livecode | DPS | Introduction to movement data (points, vectors, rasters; POSIX) | 
| 12:00 – 13:30 | Lunch | | |
| 13:30 – 14:45 | Livecode| DPS | Projecting and Plotting (proj4, transformations, visualization) |
| 14:45 – 15:00 | Afternoon Break | | |
| 15:00 – 16:30 | Hands on | | Practice plotting tracks and extracting path metrics |


## Day 3, Jan 5

### Schedule
| Time | Activity | Speaker | Topic |
| ------------- | --------------- | --- | ------------------------------------ |
| 9:00 – 10:30 | Lecture | ERD | Selection methods; Home ranges and utilization distributions |
| 10:30 – 10:45 | Morning Break | | |
| 10:45 – 12:00 | Livecode | DPS | MCP and UD (constructing home ranges, comparing results) | 
| 12:00 – 13:30 | Lunch | | |
| 13:30 – 14:45 | Livecode| DPS | RSF and SSF (obtaining environmental variables, conducting regressions) |
| 14:45 – 15:00 | Afternoon Break | | |
| 15:00 – 16:30 | Hands on | | From path to presence: transforming tracks into knowledge |


# Week 2
## Day 4, Jan 8 

### Schedule
| Time | Activity | Speaker | Topic |
| ------------- | --------------- | --- | ------------------------------------ |
| 9:00 – 10:30 | Lecture | WMG | Space-time considerations |
| 10:30 – 10:45 | Morning Break | | |
| 10:45 – 12:00 | Lecture | ERD | From LoCoH to T-LoCoH (and a-LoCoH) | 
| 12:00 – 13:30 | Lunch | | |
| 13:30 – 14:45 | Livecode| ERD | T-LoCoH derived metrics; alternative methods (Brownian bridges, AKDE) |
| 14:45 – 15:00 | Afternoon Break | | |
| 15:00 – 16:30 | Hands on | | Personal projects |

## Day 5, Jan 9

### Schedule
| Time | Activity | Speaker | Topic |
| ------------- | --------------- | --- | ------------------------------------ |
| 9:00 – 10:30 | Lecture | WMG  | Behavioral analysis; FME, CAM, and movement syndromes |
| 10:30 – 10:45 | Morning Break | | |
| 10:45 – 12:00 | Livecode | ERD | Extracting behavioral state from movement tracks (BCPA, HMM) | 
| 12:00 – 13:30 | Lunch | | |
| 13:30 – 14:45 | Livecode| DPS | Identifying movement syndromes; metrics for classification |
| 14:45 – 15:00 | Afternoon Break | | |
| 15:00 – 16:30 | Hands on | | Personal projects |

## Day 6, Jan 10
### Schedule
| Time | Activity | Speaker | Topic |
| ------------- | --------------- | --- | ------------------------------------ |
| 9:00 – 10:30 | Lecture | ERD | Simulating movement; why, when? |
| 10:30 – 10:45 | Morning Break | | |
| 10:45 – 12:00 | Livecode | ERD | Coding principles of random walks, Levy flights, other movement types | 
| 12:00 – 13:30 | Lunch | | |
| 13:30 – 14:45 | Livecode| ERD | Implementing agent-based movement models |
| 14:45 – 15:00 | Afternoon Break | | |
| 15:00 – 16:30 | Hands on | | Personal projects |

## Day 7, Jan 11
### Schedule
| Time | Activity | Speaker | Topic |
| ------------- | --------------- | --- | ------------------------------------ |
| 9:00 – 10:30 | Hands on | | More simulations |
| 10:30 – 10:45 | Morning Break | | |
| 10:45 – 12:00 | Livecode | ERD | Adding disease transmission to agent-based movement models | 
| 12:00 – 13:30 | Lunch | | |
| 13:30 – 14:45 | Lecture | WMG | Epidemiological models |
| 14:45 – 15:00 | Afternoon Break | | |
| 15:00 – 16:30 | LiveCode | WMG | Modeling Epidemics in Nova and fitting parameters |


## Day 8, Jan 12

### Schedule
| Time | Activity | Speaker | Topic |
| ------------- | --------------- | --- | ------------------------------------ |
| 9:00 – 10:30 | Hands on | | Personal projects |
| 10:30 – 10:45 | Morning Break | | |
| 10:45 – 12:00 | Hands on | | Personal projects |
| 12:00 – 13:30 | Lunch | | |
| 13:30 – 14:45 | Hands on | | Personal projects |
| 14:45 – 15:00 | Afternoon Break | | |
| 15:00 – 16:30 | Wrap Up | DPS, ERD, WMG | Wrap up,  Outstanding Questions, and Thanks|
