---
title: "Day 5 Activity"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## A true challenge!

A SSF goes through much of the same statistical theory as an RSF however
requires one to calculate available steps (not simply points), often time pulling
from the unique distribution of steps and turning angles observed in the empirical
movement path. An additional complication is extracting covariate values along
the length of the step not simply at points in space. 

Using the skills you have learned this week including:

- random number generation
- custom function writing
- path characteristic extraction
- manipulation of vector and raster data in R
- home range analysis in R

Attempt to build an SSF for a movement path of your choosing. 
When considering variables, try and use at least one continuous and one 
categorical variable as covariates.

Be sure to go through all steps:

1. estimation of range
2. selection of available points
3. extraction of covariates
4. regression 
5. model selection
6. prediction
