---
title: "Day 5 - Clustering Movement Syndromes"
author: "Dana Seidel"
date: "January 5, 2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Theory
Abrahms B, Seidel DP, Dougherty E, Hazen EL, Bograd SJ, Wilson AM, McNutt JW, Costa DP, Blake S, Brashares JS, Getz WM (2017) Suite of simple metrics reveals common movement syndromes across vertebrate taxa. Movement Ecology 5:12. doi:10.1186/s40462-017-0104-2

Abrahms B (2017) Data from: Suite of simple metrics reveals common movement syndromes across vertebrate taxa. Movebank Data Repository. doi:10.5441/001/1.hm5nk220

# Metrics
1. Mean turn angle correlation (TAC). Following Dray et al. (2010), we calculated angular autocorrelation SA as the sum of squares of chord distances between N successive turn angles ρ:

SA=1N ∑n=1N−1[(cosρn+1−cosρn)2+(sinρn+1−sinρn)2]

Thus, small chord distances resulting in low S A values correspond to high turn angle correlation [42].

2. Mean residence time (RT). Residence time was measured as the number of hours the animal spends inside a circle of a given radius centered on each location without leaving the radius for more than a specified cut-off time [38]. We tested the sensitivity of a subset of our dataset to radii of mean step length (SL), 2 x mean SL, 4 x mean SL, and 8 x mean SL, where SL was calculated as the mean Euclidean distance between successive relocations, and cut-off times of 12 and 24 h. Consistent time-use patterns were observed across these thresholds, so following van Moorter et al. (2015), we used a radius of mean SL and a 12-h cut-off time.
 
3. Mean time-to-return (T2R). Time-to-return was measured as the number of hours the animal spends beyond a specified cut-off time before its return to a circle of a given radius centered on each location [38]. We conducted the same sensitivity analysis for this metric as above, and finding consistent patterns across thresholds, we again used a radius of mean SL and a 12-h cut-off time.
 
4. Mean volume of intersection (VI). Volume of intersection was measured by the overlap between monthly 95% kernel density home ranges [43, 44]. Volume of intersection varies between 0 and 1, with increasing values corresponding to increasing overlap between monthly home ranges. VI is thus a measure of home range stability.
 
5. Maximum net squared displacement (MNSD). Maximum net squared displacement was calculated as the maximum squared Euclidean displacement from the first relocation of the trajectory over the full course of the trajectory [45]. To make comparisons among individuals across species that have orders of magnitude different motion capacities, we scaled this parameter for each individual by dividing by the smallest MNSD observed for its species.

# Principle Component Analysis
> To elucidate any underlying structure in our dataset, we performed a principal components analysis (PCA) for the above metrics calculated from our empirical datasets using the prcomp function in the R stats library [29]. PCA is a widely used technique for summarizing a multivariate dataset into a reduced number of uncorrelated dimensions, or principal components, while minimizing the loss of information in the original dataset [48]. We used the Broken-stick criterion to retain important composite (PC) axes, in which components are retained if their eigenvalues exceed those expected by random data [43]. Comparative analyses of component retention methods have shown the Broken-stick model to be among the most reliable techniques [48, 49]. To normalize the dataset for this analysis we first log-transformed the data, followed by centering around the mean and dividing by the variance [50].

# Clustering
> Finally, we applied Ward’s agglomerative hierarchical clustering algorithm to the resulting PCA values [51] using the hclust function in the R stats library [29]. This approach clusters the most similar pair of points based on their squared Euclidean distance at each stage of the algorithm, and is an efficient method to identify clusters based on minimum within-cluster variance without making an a priori determination of the number of clusters to generate [52]. These clusters can be viewed as functional movement groups, analogous to functional types first theorized for plant communities, which provide a non-phylogenetic classification based on shared responses to environmental conditions [53]. To determine the significance of the resulting cluster arrangement, we calculated p-values for each cluster via multi-scale bootstrap resampling with 1000 bootstrap replications using the R package Pvclust [54, 55]. By simulating the following idealized movers and determining their cluster assignments, we were able to identify these clusters by movement syndrome.
