---
title: "Disease_ABM"
author: "Eric Dougherty & Dana Seidel"
date: "January 2, 2018"
output:
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

We have created some pretty complex functions at this point. We have seen simple random walks, empirically-based steps, multi-state movement models, and landscape-dependent movement. What we are going to do today is work on an agent-based movement model with an epidemiology component. Rather than simply observing movement behavior, we are going to see if there are any emergent patterns or properties that we can measure. 

Our goal is to represent two different transmission pathways: indirect and direct. Pathogens can be transmitted in a vast number of different ways, but we will simplify the processes into indirect (where the infective stage is shed into environment where a susceptible individual encounters it) and direct (where the infective stage is transmitted between individuals without an external reservoir).

## Indirect Transmission

We will begin with the indirect case. I am going to describe a hypothetical pathogen and then we will go through how we can model it in an agent-based framework. Let's say that our pathogen is shed by an infected individual when it defecates. The pathogen remains viable in the feces for approximately 7 to 11 days (links have been drawn between moisture and duration of infectiveness on the landscape, though we can treat it as a stochastic process). Individuals are attracted to the deposition sites (though the exact mechanism remains unclear). Researchers have observed that animals within approximately 50 meters will almost inevitably investigate the infectious reservoir, and only a small dose is required to induce infection. About 20% of individuals can mount an immune response to the pathogen, and age is a major determinant in this process (older adults tend to succumb while younger adults can fight off infection).

## Direct Transmission

Next, we will move on to the direct transmission case.
